//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Album
{
    public int AlbumId { get; set; }
    public string Title { get; set; }
    public int UserId { get; set; }
    public System.DateTime Date { get; set; }
}

public partial class Comment
{
    public int CommentId { get; set; }
    public int PostId { get; set; }
    public int UserId { get; set; }
    public string Body { get; set; }
    public System.DateTime Date { get; set; }
}

public partial class Photo
{
    public int PhotoId { get; set; }
    public int AlbumId { get; set; }
    public string Titile { get; set; }
    public string Url { get; set; }
    public string ThumbnailUrl { get; set; }
}

public partial class Post
{
    public int PostId { get; set; }
    public int UserId { get; set; }
    public string Title { get; set; }
    public string Body { get; set; }
    public System.DateTime Date { get; set; }
    public string Category { get; set; }
}

public partial class Todo
{
    public int TodoId { get; set; }
    public int UserId { get; set; }
    public string Title { get; set; }
    public bool Completed { get; set; }
}

public partial class User
{
    public int UserId { get; set; }
    public string Name { get; set; }
    public string Email { get; set; }
    public string Country { get; set; }
    public string Gander { get; set; }
    public string Company { get; set; }
    public string Profession { get; set; }
    public string Password { get; set; }
    public System.DateTime Date { get; set; }
}
